#!/usr/bin/env bash
# Regenerate the built-in model pricing table from OpenRouter.
#
#   scripts/generate-pricing.sh
#
# Writes apple/Sources/TokenWiseCore/PricingGenerated.swift. Rates are vendor
# list prices as published by OpenRouter (verified to match OpenAI's and
# Anthropic's own published rates), converted to USD per million tokens.
#
# The table is vendored rather than fetched at runtime: TokenWiseCore is
# Foundation-only and the App Store build is sandboxed, so pricing must work
# offline. Re-run this when a vendor ships or reprices a model.
#
# Curated entries in Pricing.swift take precedence over anything generated
# here — see `PricingTable.curated`.

set -euo pipefail
cd "$(dirname "$0")/.."

OUT="apple/Sources/TokenWiseCore/PricingGenerated.swift"
API="https://openrouter.ai/api/v1/models"

# Vendors whose models plausibly show up in a Claude Code / Codex session log.
VENDORS='^(anthropic|openai|google|deepseek|minimax|moonshotai|z-ai|x-ai|qwen|mistralai|meta-llama|cohere)/'

echo "==> fetching $API"
RAW="$(curl -fsSL "$API")"
COUNT="$(jq -r '.data | length' <<<"$RAW")"
echo "==> $COUNT models returned"

# One TSV row per matchable pattern: pattern, input, cacheWrite, cacheRead, output.
# Model ids are written with dots upstream (`claude-opus-4.5`, `gpt-5.5`) but
# Claude Code logs them with dashes (`claude-opus-4-5`), so emit both spellings.
ROWS="$(jq -r --arg vendors "$VENDORS" '
  def perM($p): (($p // "0" | tonumber) * 1000000 * 10000 | round) / 10000;
  .data[]
  | select(.id | test($vendors))
  | select((.architecture.output_modalities // ["text"]) | index("text"))
  | select(.id | test(":free$") | not)
  | (.id | split("/")[1:] | join("/")) as $name
  | [perM(.pricing.prompt),
     perM(.pricing.input_cache_write),
     perM(.pricing.input_cache_read),
     perM(.pricing.completion)] as $rates
  | ([$name, ($name | gsub("\\."; "-"))] | unique)[] as $pattern
  | select($pattern | length >= 3)
  | [$pattern] + $rates
  | @tsv
' <<<"$RAW" | LC_ALL=C sort -t"$(printf '\t')" -k1,1)"

# Two ids can normalize onto one pattern; keep the first deterministically.
ENTRIES="$(awk -F'\t' '!seen[$1]++ { printf "        (\"%s\", %s, %s, %s, %s),\n", $1, $2, $3, $4, $5 }' <<<"$ROWS")"
N="$(wc -l <<<"$ENTRIES" | tr -d ' ')"

cat > "$OUT" <<SWIFT
// Generated by scripts/generate-pricing.sh — do not edit by hand.
//
// Source: $API (vendor list prices, USD per million tokens)
// Snapshot: $(date -u +%Y-%m-%d), $N patterns from $COUNT published models.
//
// Model ids appear in both dotted and dashed spelling because Codex logs
// \`gpt-5.5\` while Claude Code logs \`claude-opus-4-8\`. Curated entries in
// Pricing.swift override anything here.

extension PricingTable {
    /// (pattern, input, cacheWrite, cacheRead, output) per million tokens.
    static let generated: [(String, Double, Double, Double, Double)] = [
$ENTRIES
    ]
}
SWIFT

echo "==> wrote $OUT ($N patterns)"
